name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag httpsluanfernandes01/family-cash-card-service:latest
    - name: Login to Docker Hub
      run: docker login -u httpsluanfernandes01 -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Push image to Docker Hub
      run: docker push httpsluanfernandes01/family-cash-card-service:latest
